name: cie_app
description: A new Flutter app to handle with courses in english of HM.

version: 1.5.3+703

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: "^0.3.2"
  firebase_analytics: "^1.0.3"
  path_provider: "^0.4.1"
  cupertino_icons: "^0.1.2"
  url_launcher: "^3.0.3"
  flutter_html_view: "^0.5.8"
  progress_hud: "^1.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - res/images/hm_logo.png
    - res/images/karlstrasse.png
    - res/images/lothstrasse.png
    - res/images/pasing.png
    - res/images/hm_app_icon.png
    - res/images/AppLogo_Transparent.png
